controller_list:
 - name: r_arm
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - r_joint1
      - r_joint2
      - r_joint3
      - r_joint4
      - r_joint5
      - r_joint6

 - name: l_arm
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - l_joint1
      - l_joint2
      - l_joint3
      - l_joint4
      - l_joint5
      - l_joint6
